### ISSUE TITLE
CopyThreads throwing error when compiling to Attiny85

### ISSUE THREAD

**Issue by max0410** [jensh/CopyThreads#1]
When I try compiling the example program CTBlink.ino to my arduino nano it works just fine. But, when I changed the board in Tools settings to Atting85 I get this error:
```
C:\Users\Userl\Documents\Arduino\libraries\CopyThreads\src\Cth.cpp: In function 'void loop()':

C:\Users\User\Documents\Arduino\libraries\CopyThreads\src\Cth.cpp:70:6: error: 'serialEventRun' was not declared in this scope

  if (serialEventRun) serialEventRun();

      ^

exit status 1
Error compiling for board ATtiny25/45/85.
```

Is there any solution or bit of code that I can use to fix this issue?

**Comment by jensh** [comment]
Probably this line is not needed for ATTinys. You can try to comment this line out:
```C
 //  if (serialEventRun) serialEventRun();
```

**Comment by max0410** [comment]
It worked! Thanks a lot!
